//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Clan2.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FILETYPE                    101
#define IDD_RGB                         102
#define IDD_QT_DIALOG                   102
#define IDD_RLE4                        103
#define IDD_RLE8                        104
#define IDD_1                           106
#define IDD_4                           107
#define IDD_8                           108
#define IDD_24                          109
#define IDD_FILETYPEGROUP               110
#define IDD_BPP                         111
#define IDR_MAINFRAME                   128
#define IDR_CLAN2TYPE                   129
#define IDD_QT                          129
#define IDD_CED_OPTIONS                 130
#define IDD_EDIT_GOTO_LINE              133
#define IDD_HELP_WINDOW                 135
#define IDD_LOCATE_DIR                  136
#define IDD_OPENDIR                     137
#define IDD_EDIT_SNDSYNC                141
#define IDD_ENTER_ASCII                 143
#define IDD_NEXT_TIER                   144
#define IDD_TIER_SELECT                 145
#define IDD_CLAN                        146
#define IDR_MOVIEFRAME                  157
#define IDD_EDIT_MOR_OPTIONS            157
#define IDD_MPEG                        164
#define IDD_VIEW_SET_TAB                167
#define IDD_EDIT_URL_ADDRESS            168
#define IDD_GET_FILENAME                169
#define IDD_PICT                        170
#define IDD_FSTRUCT_VIEWER              181
#define IDD_MYHELP                      183
#define IDB_MYHELP                      184
#define IDD_EDIT_LINENUM_SIZE           184
#define IDD_SOUND_ANA_APP               185
#define IDD_INSERT_DIALOG               186
#define IDD_PLAYBACK_CONTROL            187
#define IDD_TEXT                        188
#define IDD_FIND_STRING_U               189
#define IDD_CONST_ST_NUMBER_U           190
#define IDD_EDIT_DO_STRING_U            191
#define IDD_EDIT_MACRO_U                192
#define IDR_MAINFRAMEU                  192
#define IDD_ENTER_COMMENTS_U            193
#define IDD_REPLACE_CONT_U              194
#define IDD_REPLACE_STRING_U            195
#define IDD_STDIN_U                     196
#define IDD_EDIT_F5_OPTION              197
#define IDD_CLAN_SP_CHARS               198
#define IDD_WEB_DATA                    199
#define IDD_WEB_GETPASSWD               200
#define IDD_KEYWORD_COLOR_U             201
#define IDR_CLAN2CEX                    202
#define IDD_CLAN_RECALL                 202
#define IDR_CLAN2CDC                    203
#define IDI_ICON1                       204
#define IDR_CLAN2UTIL                   204
#define IDD_UPDATE_OPTION               205
#define IDD_PROGRESS                    206
#define IDD_CLAN_SEARCH                 207
#define IDD_CLAN_TIERS                  208
#define IDD_SEARCH_MORHELP              209
#define IDD_CLAN_TIERS_SELECT_FILES     210
#define IDD_CLAN_TIERS_SELECT           211
#define IDD_CLAN_EVAL_SELECT            212
#define IDD_TXT_FILE                    213
#define IDD_EDIT_THUMBNAIL_SIZE         214
#define IDD_OPENMEDIAFILE               215
#define IDC_CEDO_CHECKPOINT_E           1000
#define IDC_BUTTON_PLAY                 1000
#define IDC_CEDO_CODES_B                1001
#define IDC_LIST1                       1001
#define IDC_CEDO_KEYBIND_B              1002
#define IDC_EDIT_FROM                   1003
#define IDC_CEDO_STATIC0                1004
#define IDC_EDIT_POS                    1004
#define IDC_Apply                       1004
#define IDC_OK                          1004
#define IDC_CEDO_STATIC1                1005
#define IDC_EDIT_TO                     1005
#define IDC_CEDO_KEYBIND_F              1006
#define IDC_BUTTON_SAVE                 1006
#define IDC_CEDO_CODES_F                1007
#define IDC_CEDO_STATIC2                1008
#define IDC_CEDO_CLAN_LIMIT             1009
#define IDC_CEDO_STATIC3                1010
#define IDC_CEDO_OPEN_CLAN              1011
#define IDC_CEDO_CREATE_BACKUP          1012
#define IDC_CEDO_START_EDITOR           1013
#define IDC_CEDO_CURSOR_PERC            1014
#define IDC_CEDO_WRAP_LINES             1015
#define IDC_check_language              1015
#define IDC_CEDO_WRAP_CLAN_LINES        1016
#define IDC_check_corpus                1016
#define IDC_CEDO_STATIC4                1017
#define IDC_CEDO_CHAT_ALWAYS            1018
#define IDC_check_age                   1018
#define IDC_CEDO_CHAT_NEVER             1019
#define IDC_check_sex                   1019
#define IDC_CEDO_CHAT_AUTO              1020
#define IDC_check_group                 1020
#define IDC_FIND_STRING                 1021
#define IDC_check_SES                   1022
#define IDC_EDIT_language               1025
#define IDC_EDIT_corpus                 1026
#define IDC_FIND_CASE_SEN               1027
#define IDC_FIND_BACKWARD               1028
#define IDC_EDIT_age                    1028
#define IDC_EDIT_sex                    1029
#define IDC_FIND_STATIC1                1030
#define IDC_EDIT_group                  1030
#define IDC_EDIT_GOTO_LINENUMBER        1031
#define IDC_EDIT_setting                1031
#define IDC_REPLACE_CASE_SEN            1032
#define IDC_EDIT_SES                    1032
#define IDC_REPLACE_THIS                1033
#define IDC_REPLACE_SKIP                1034
#define IDC_REPLACE_SKIP_THIS           1034
#define IDC_EDIT_role                   1034
#define IDC_EDIT_REPLACE_STRING         1035
#define IDC_DIR                         1035
#define IDC_EDIT_REPLACE_WITH           1036
#define IDC_HELP_INPUT                  1037
#define IDC_all                         1037
#define IDC_HELP_SHOW                   1038
#define IDC_Split                       1040
#define IDC_EDIT_NUMBER                 1042
#define IDC_EDIT_STRING                 1043
#define IDC_DONOTHING                   1044
#define IDC_DISPLAY_WAVE                1045
#define IDC_DISPLAY_AND_PLAY            1046
#define IDC_Sid                         1047
#define IDC_ENTER_ASCII_SHOW            1048
#define IDC_ENTER_ASCII_INPUT           1049
#define IDC_NEXT_TIER                   1050
#define IDC_TIER_INCLUDE                1051
#define IDC_participant                 1051
#define IDC_TIER_EXCLUDE                1052
#define IDC_setting                     1052
#define IDC_TIER_RESET                  1053
#define IDC_corpus                      1053
#define IDC_TIER_LIST                   1054
#define IDC_language                    1054
#define IDC_CONST_LIST                  1055
#define IDC_age                         1055
#define IDC_CLAN_WD                     1056
#define IDC_sex                         1056
#define IDC_CLAN_RUN                    1057
#define IDC_group                       1057
#define IDC_CLAN_OD                     1058
#define IDC_SES                         1058
#define IDC_CLAN_LIB                    1059
#define IDC_role                        1059
#define IDC_CLAN_LIB_ST                 1062
#define IDC_CLAN_HELP                   1063
#define IDC_CLAN_ICON_PROG              1064
#define IDC_CLAN_OD_ST                  1065
#define IDC_CLAN_WD_ST                  1066
#define IDC_CLAN_PROG                   1068
#define IDC_CLAN_FILEIN                 1069
#define IDC_CLAN_COMMANDS               1070
#define IDC_CLAN_OPT                    1071
#define IDC_STDIN_INPUT                 1072
#define IDC_CLAN_SEARCH                 1073
#define IDC_CLAN_FILEOUT                1074
#define IDC_LIST_OF_DATA                1074
#define IDC_SELECTED_FILENAME           1075
#define IDC_REMOVE                      1076
#define IDC_CLEAR                       1077
#define IDC_VERSION                     1078
#define IDC_CEDO_DISAMBIG               1080
#define IDC_CEDO_PROSODIC               1081
#define IDC_CEDO_ILLIGAL_CHARS          1082
#define IDC_STRINGNUMBER                1083
#define IDC_CEDO_CAIN_MODE              1084
#define IDC_EDIT_GRAM_NAME              1085
#define IDC_EDIT_LEX_NAME               1086
#define IDC_CEDO_ID_TIER                1096
#define IDC_MEDIAPLAYER1                1098
#define IDC_MPG_EDIT_POS                1100
#define IDC_BORDER                      1101
#define IDC_SAVE_BUTTON                 1102
#define IDC_REPEAT_BUTTON               1103
#define IDC_PLAY_BUTTON                 1103
#define IDC_END_BUTTON                  1104
#define IDC_MPG_EDIT_TO                 1105
#define IDC_BEG_BUTTON                  1106
#define IDC_MPG_EDIT_FROM               1107
#define IDC_EDIT_DO_STRING_VAL          1108
#define IDC_FIND_WRAP                   1109
#define IDC_FIND_INS_RETURN             1110
#define IDC_FIND_INS_TAB                1111
#define IDC_REPLACE_FROM_FILE           1112
#define IDC_REPLACE_INS_RETURN          1113
#define IDC_REPLACE_INS_TAB             1114
#define IDC_REPLACE_FROM_FILE2          1115
#define IDC_REPLACE_USE_FILE            1115
#define IDC_EDIT_REPLACE_CONT_STRING    1121
#define IDC_EDIT_REPLACE_CONT_WITH      1122
#define IDC_REPLACE_CONT_THIS           1123
#define IDC_REPLACE_CONT_SKIP_THIS      1124
#define IDC_REPLACE_ALL                 1125
#define IDC_SET_BEGIN                   1130
#define IDC_SET_END                     1131
#define IDC_SPIN1                       1135
#define IDC_EDIT_URL_ADD_NAME           1141
#define IDC_EDIT_URL_USEURL             1142
#define IDC_REPLACE_INS_BULLET          1144
#define IDC_BUTTON1                     1145
#define IDC_FIND_INS_BULLET             1145
#define IDC_EXPAND_ALL                  1145
#define IDC_CLAN_MOR_LIB                1145
#define IDC_ADD_ALL                     1145
#define IDC_PLAYBACK_OPENMEDIA          1145
#define IDC_WEB_CHILDES                 1145
#define IDC_DEL_ONE                     1145
#define IDC_CANCEL                      1145
#define IDC_SEARCH_MORHELP              1145
#define IDC_TIER_MORE_CHOICES           1145
#define IDC_GET_FILENAME                1146
#define IDC_FIND_FROM_FILE              1147
#define IDC_FIND_FILE_LIST              1148
#define IDC_FIND_LIST_FNAME             1149
#define IDC_CEDO_WRAP_CHAT              1151
#define IDC_TREE1                       1152
#define IDC_COLLAPSE_ALL                1153
#define IDC_GOOD                        1155
#define IDC_BAD                         1156
#define IDC_SPEAKER_TIER                1158
#define IDC_DEP_TIER                    1159
#define IDC_COMMENTS                    1160
#define IDC_CLAN_MOR_LIB_ST             1161
#define IDC_SKIP_NEXT                   1162
#define IDC_CEDO_MIXED_STEREO           1163
#define IDC_CEDO_UPDATE_CLAN            1164
#define IDC_EDIT_DELAY                  1165
#define IDC_EDIT_MSEC                   1166
#define IDC_QD_HELP                     1167
#define IDC_MYHELP_PICT                 1169
#define IDC_MPG_EDIT_DELAY              1170
#define IDC_MPG_EDIT_MSEC               1171
#define IDC_MPG_HELP                    1172
#define IDC_EDIT_LINENUM_SIZE           1173
#define IDC__CEDO_CHAT_LINENUM          1174
#define IDC_PRAAT                       1175
#define IDC_PITCHWORKS                  1176
#define IDC_PLAYBACK_SHIFT_RATE         1178
#define IDC_PLAYBACK_SPEED              1179
#define IDC_PLAYBACK_PAUSE_LEN          1180
#define IDC_SEGMENT_LENGTH              1181
#define IDC_PLAYBACK_LOOP_NUMBER        1182
#define IDC_PLAYBACK_CONTROL_ENABLE     1183
#define IDC_PLAYBACK_CURSOR_POS         1184
#define IDC_PLAYBACK_SLIDER             1185
#define IDC_TEXTBULLET                  1186
#define IDC_PLAYBACK_TOTAL_LEN          1187
#define IDC_EDIT_LINENUM_EVERYLINE      1187
#define IDC_EDIT_LINENUM_MAINTIER       1188
#define IDC__CEDO_INPUT_RAW_DATA        1189
#define IDC_BET                         1194
#define IDC_BEL                         1195
#define IDC_CLAN_SP_CHARS               1196
#define IDC_CED_SPCKeyShortcuts         1197
#define IDC_WEB_DATA                    1198
#define IDC_WEB_TALKBANK                1199
#define IDC_WEB_PASSWD                  1200
#define IDC_WEB_USERNAME                1201
#define IDC_EDIT_PROXY_ADDRESS          1202
#define IDC_EDIT_PROXY_PORT             1203
#define IDC_EDIT_WORD                   1204
#define IDC_DEL_ALL                     1205
#define IDC_APPLY_COLOR                 1208
#define IDC_COLOR_ENTIRE                1209
#define IDC_MATCH_ENTIRE                1210
#define IDC_CASE                        1211
#define IDC_TREAT_AS                    1212
#define IDC_EDIT_COLOR                  1213
#define IDC_COLOR_SWATCH                1216
#define IDC_F5_Offset                   1217
#define IDC_ADD_ONE                     1218
#define IDC_DESKTOP                     1219
#define IDC_CON                         1222
#define IDC_F5_STR                      1223
#define IDC_CEDO_RESTORECURSOR          1224
#define IDC_CEDO_RESTORE_CURSOR         1224
#define IDC_IDS_SPEAKERID               1225
#define IDC_COMBOBOXEX2                 1226
#define IDC_IDS_ROLE                    1226
#define IDC_IDS_LAN                     1227
#define IDC_IDS_CORPUS                  1228
#define IDC_IDS_CODE                    1229
#define IDC_IDS_ABOUT                   1230
#define IDC_IDS_Y1                      1231
#define IDC_IDS_M1                      1232
#define IDC_IDS_D1                      1233
#define IDC_IDS_Y2                      1234
#define IDC_IDS_M2                      1235
#define IDC_IDS_D2                      1236
#define IDC_IDS_GROUP                   1238
#define IDC_IDS_SES                     1239
#define IDC_IDS_EDUCATION               1240
#define IDC_IDS_UFID                    1241
#define IDC_IDS_SPNAME                  1242
#define IDC_IDS_DEL                     1243
#define IDC_IDS_CREATE                  1244
#define IDC_IDS_COPY                    1245
#define IDC_IDS_UNK                     1246
#define IDC_IDS_MALE                    1247
#define IDC_IDS_FEMALE                  1249
#define IDC_CLAN_RECALL                 1249
#define IDC_CLAN_RECALLS                1250
#define IDC_UPDATE_SKIP                 1251
#define IDC_UPDATE_NO_CHECK             1252
#define IDC_UPDATE_MESSAGE              1253
#define IDC_UPDATE_CLAN                 1254
#define IDC_PROGRESS                    1255
#define IDC_BOT_CANCEL                  1256
#define IDC_CLAN_TIER_TEXT              1258
#define IDC_CLAN_INCLUDE                1259
#define IDC_CLAN_EXCLUDE                1260
#define IDC_CLAN_EXCLUDE_ALL_MAIN       1261
#define IDC_CLAN_M_TIER                 1262
#define IDC_CLAN_D_TIER                 1263
#define IDC_CLAN_H_TIER                 1264
#define IDC_SEARCH_FROM_FILE            1264
#define IDC_SEARCH_INCLUDE              1265
#define IDC_CLAN_R_TIER                 1265
#define IDC_SEARCH_EXCLUDE              1266
#define IDC_CLAN_ID_TIER                1266
#define IDC_SEARCH_LIST_FNAME           1267
#define IDC_SEARCH_WORD                 1268
#define IDC_SEARCH_CODE                 1269
#define IDC_SEARCH_POSTCODE             1270
#define IDC_SEARCH_LANGCODE             1271
#define IDC_SEARCH_CODE_ITSELF          1272
#define IDC_SEARCH_CODE_DATA            1273
#define IDC_SEARCH_MOR                  1274
#define IDC_SEARCH_TEXT                 1275
#define IDC_SEARCH_FILE                 1276
#define IDC_SEARCH_POS_S                1277
#define IDC_SEARCH_PRESETS              1278
#define IDC_SEARCH_MOR_O                1279
#define IDC_TIER_SELECT_PAT             1279
#define IDC_SEARCH_POS_E                1280
#define IDC_TIER_SELECT_PATS            1280
#define IDC_SEARCH_STEM_S               1281
#define IDC_EXCLUDE_ALL_MAIN            1281
#define IDC_SEARCH_STEM_E               1282
#define IDC_INCLUDE_ALL_HEADER          1282
#define IDC_SEARCH_PREFIX_S             1283
#define IDC_SELECT_ALL_SPEAKER          1283
#define IDC_SEARCH_PREFIX_E             1284
#define IDC_SELECT_ALL_DEP              1284
#define IDC_SEARCH_SUFFIX_S             1285
#define IDC_SELECT_T1                   1285
#define IDC_SEARCH_SUFFIX_E             1286
#define IDC_SELECT_T16                  1286
#define IDC_SEARCH_FUSION_S             1287
#define IDC_SELECT_T2                   1287
#define IDC_SEARCH_FUSION_E             1288
#define IDC_SELECT_T17                  1288
#define IDC_SEARCH_TRANS_S              1289
#define IDC_SELECT_T3                   1289
#define IDC_SEARCH_TRANS_E              1290
#define IDC_SELECT_T4                   1290
#define IDC_SELECT_T5                   1291
#define IDC_SELECT_T6                   1292
#define IDC_SELECT_T7                   1293
#define IDC_SELECT_T8                   1294
#define IDC_SELECT_T9                   1295
#define IDC_SELECT_T10                  1296
#define IDC_SELECT_T11                  1297
#define IDC_SELECT_T12                  1298
#define IDC_SELECT_T13                  1299
#define IDC_SELECT_T14                  1300
#define IDC_SELECT_T15                  1301
#define IDC_SELECT_T18                  1302
#define IDC_SELECT_T19                  1303
#define IDC_SELECT_T20                  1304
#define IDC_SELECT_T21                  1305
#define IDC_SELECT_T22                  1306
#define IDC_SELECT_PAGE_NEXT            1308
#define IDC_SELECT_PAGE                 1309
#define IDC_SELECT_T23                  1310
#define IDC_CLAN_PROGM                  1310
#define IDC_SELECT_T24                  1311
#define IDC_PORTF_DDB                   1311
#define IDC_SELECT_T25                  1312
#define IDC_PORTF_UDB                   1312
#define IDC_SELECT_T26                  1313
#define IDC_PORTF_ANOMIC                1313
#define IDC_SELECT_T27                  1314
#define IDC_PORTF_GLOBAL                1314
#define IDC_SELECT_READING              1315
#define IDC_SELECT_T28                  1316
#define IDC_PORTF_CONTROL               1316
#define IDC_SELECT_T29                  1317
#define IDC_PORTF_BROCA                 1317
#define IDC_SELECT_T30                  1318
#define IDC_PORTF_WERNICKE              1318
#define IDC_PORTF_CONDUCTION            1319
#define IDC_SELECT_PAGE_PREV            1320
#define IDC_PORTF_TRANS                 1320
#define IDC_PORTF_TRANM                 1321
#define IDC_PORTF_NOTAPH                1322
#define IDC_PORTF_AGE                   1323
#define IDC_PORTF_MALE                  1324
#define IDC_PORTF_FEMALE                1325
#define IDC_PORTF_FLUENT                1326
#define IDC_PORTF_NONF                  1327
#define IDC_LABEL                       1327
#define IDC_PORTF_ALL                   1328
#define IDC_PORTF_GEMD                  1329
#define IDC_PORTF_GEMS                  1330
#define IDC_EDIT_THUMBNAIL_SIZE         1330
#define IDC_PORTF_SPEECH                1331
#define IDC_LIST_OF_MEDIA_FILES         1331
#define IDC_PORTF_CINDERELLA            1332
#define IDC_REPLACE_LIST_FNAME          1332
#define IDC_PORTF_IMPEVENT              1333
#define IDC_PORTF_CAT                   1334
#define IDC_PORTF_UMBRELLA              1335
#define IDC_PORTF_STROKE                1336
#define IDC_PORTF_FLOOD                 1337
#define IDC_PORTF_SANDWICH              1338
#define IDC_PORTF_SANDWICH2             1339
#define IDC_PORTF_WINDOW                1339
#define ID_CHOOSE_FONT                  32771
#define ID_VIEW_SETFONT                 32772
#define ID_CHOOSE_DEFAULT_FONT          32773
#define ID_SELECT_ALL                   32774
#define ID_EDIT_OPTIONS_CEDOPTIONS      32775
#define ID_EDIT_ENTER_SELECTION         32778
#define ID_EDIT_FIND_SAME               32779
#define ID_EDIT_GOTO                    32781
#define ID_EDIT_TO_UPPER                32782
#define ID_EDIT_TO_LOWER                32783
#define ID_CLAN_CLANWINDOW              32790
#define ID_MACROS_DEFINE                32791
#define ID_MODE_CODER                   32792
#define ID_MODE_CHECKFILE               32793
#define ID_MODE_CHATMODE                32794
#define ID_MODE_SOUNDMODE               32795
#define ID_MODE_PLAYCONT                32796
#define ID_MODE_LINKSND                 32797
#define ID_MACROS_1                     32798
#define ID_MACROS_2                     32799
#define ID_MACROS_3                     32800
#define ID_MACROS_4                     32801
#define ID_MACROS_5                     32802
#define ID_MACROS_6                     32803
#define ID_MACROS_7                     32804
#define ID_MACROS_8                     32805
#define ID_MACROS_9                     32806
#define ID_MACROS_10                    32807
#define ID_SPEAKERS_1                   32808
#define ID_SPEAKERS_2                   32809
#define ID_SPEAKERS_3                   32810
#define ID_SPEAKERS_4                   32811
#define ID_SPEAKERS_5                   32812
#define ID_SPEAKERS_6                   32813
#define ID_SPEAKERS_7                   32814
#define ID_SPEAKERS_8                   32815
#define ID_SPEAKERS_9                   32816
#define ID_SPEAKERS_10                  32817
#define ID_SPEAKERS_UPDATE              32818
#define ID_CHOOSE_CLAN_FONT             32819
#define ID_EDIT_OPTIONS_SETDEPFILE      32820
#define ID_MODE_DISAMBIG                32821
#define ID_MODE_TIER_EXCLUSION          32822
#define ID_MODE_PLAYSOUND               32823
#define ID_MODE_PLAYMOVIE               32824
#define ID_MODE_SOUNDTOTEXTSYNC         32825
#define ID_EDIT_MOR_OPTIONS             32826
#define ID_MODE_EXPEND_BULLETS          32827
#define ID_FILE_OPEN_MOVIE              32828
#define ID_FILE_NEW_MOVIE               32829
#define ID_MODE_START_PLAY              32829
#define ID_FILE_OPENRAW                 32830
#define ID_UNDERLINE                    32831
#define ID_EDIT_REPLACEFIND             32832
#define ID_ITALIC                       32833
#define ID_MODE_CAMODE                  32834
#define ID_MODE_PLAYCONTMOV             32835
#define ID_SET_TAB                      32836
#define ID_EDIT_URL_ADD                 32844
#define ID_CHOOSE_COMMAND_FONT          32845
#define ID_MODE_TRANSMEDIA              32847
#define ID_MODE_SEND_TO_PRAAT           32848
#define ID_FILE_SAVE_CLIP               32849
#define ID_FUNC_SHORTCUTS               32850
#define ID_FUNCS_SHORTCUTS_FILE         32851
#define ID_LINENUMBER_SIZE              32852
#define ID_SOUND_ANALIZER_APP           32853
#define ID_INSERT_DIALOG                32854
#define ID_PLAYBACK_CONTROL             32855
#define ID_MODE_UTF8                    32856
#define ID_F5_OPTION                    32857
#define ID_CLAN_CA_CHARS                32858
#define ID_BOLD                         32859
#define ID_PLAIN                        32860
#define ID_WEB_DATA                     32861
#define ID_COLOR_WORDS                  32862
#define ID_COLOR_KEYWORDS               32863
#define ID_TOGGLE_MOVIE_TEXT            32864
#define ID_MODE_HIDETIERSIN             32865
#define ID_MODE_HIDE_TIERS              32866
#define id_                             32867
#define ID_TIERS_IDHEADERS              32868
#define ID_MODE_CONTINUOUSSKIPPLAY      32869
#define ID_MODE_PLAYCONTSKIP            32870
#define ID_EDIT_THUMBNAILSSETTINGS      32871
#define ID_EDIT_THUMBNAILS              32872
#define ID_FILE_SELECTMEDIAFILE         32873
#define ID_EDIT_ResetAllOptions         32874
#define ID_EDIT_RESETOPTIONS            32875
#define IDS_CANT_INIT_QUARTZ            61450
#define IDS_CANT_RENDER_FILE            61451
#define IDS_CANT_PLAY                   61452
#define IDS_CANT_PAUSE                  61453
#define IDS_CANT_STOP                   61454

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32876
#define _APS_NEXT_CONTROL_VALUE         1333
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
